resource_types:
- name: semver
  type: registry-image
  source:
    repository: concourse/semver-resource


resources:
  - name: repository
    type: git
    source:
      uri: https://((github-token))@github.com/cirocosta/dmesg_exporter
      ignore_paths: [ ./VERSION ]

  - name: builder
    type: registry-image
    source:
      repository: cirocosta/builder

  - name: container-image
    type: registry-image
    source:
      repository: cirocosta/dmesg_exporter
      username: ((docker-user))
      password: ((docker-password))

  - name: version
    type: semver
    source:
      driver: git
      uri: https://((github-token))@github.com/cirocosta/dmesg_exporter
      branch: master
      file: ./VERSION
      git_user: Ciro S. Costa <cscosta@pivotal.io>


jobs:
  - name: build
    public: true
    plan:
      - in_parallel:
        - {get: repository, trigger: true}
        - {get: version, trigger: true}
        - {get: builder}
      - in_parallel:
        fail_fast: true
        steps:
          - task: build-image
            image: builder
            privileged: true
            file: repository/ci/tasks/build.yml
          - task: tests
            image: builder
            privileged: true
            params: {TARGET: tests}
            output_mapping: {image: unused}
            file: repository/ci/tasks/build.yml
      - put: container-image
        inputs: [image, version]
        get_params: {format: oci}
        params:
          image: image/image.tar
          additional_tags: version/version
