{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "dmesg.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "dmesg.name" . }}
    helm.sh/chart: {{ include "dmesg.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  groups:
  {{- with .Values.prometheusRule.rules }}
    - name: {{ template "dmesg.name" $ }}
      rules:
        {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}